### ISSUE TITLE
Publish LUNI.AI on Zoom's marketplace

### ISSUE THREAD

**Issue by chris-miaskowski** [luni-ai/public-roadmap#54]
review process https://developers.zoom.us/docs/distribute/app-review-process/

https://marketplace.zoom.us/develop/apps/Lpv08ydqQSmdh1BL4OoH5Q/information?check=true

## [Step 1: Submission completeness and branding review](https://developers.zoom.us/docs/distribute/app-submission/submission-checklist/)

- [x] [1. App name and branding requirements](https://developers.zoom.us/docs/distribute/app-submission/submission-checklist/#1-app-name-and-branding-requirements)
- [x] [2. Complete App Descriptions](https://developers.zoom.us/docs/distribute/app-submission/submission-checklist/#2-complete-app-descriptions)
- [ ] [3. Adding images and videos](https://developers.zoom.us/docs/distribute/app-submission/submission-checklist/#3-adding-images-and-videos)
  - [ ] [Resources](https://www.canva.com/design/DAF59oHobQY/qCAnCSrT_0RAMRSwiut8SQ/edit)
- [x] [4. Provide a Privacy Policy URL](https://developers.zoom.us/docs/distribute/app-submission/submission-checklist/#4-provide-a-privacy-policy-url) | Issue: https://github.com/luni-ai/public-roadmap/issues/55
  - [x] create an email for security/privacy related stuff
  - [x] prepare privacy policy for California residents 
  - [x] publish on luni.ai/privacy-policy and update Zoom marketplace information with the link
- [x] [5. Provide a Terms of Use URL](https://developers.zoom.us/docs/distribute/app-submission/submission-checklist/#5-provide-a-terms-of-use-url) | https://github.com/luni-ai/public-roadmap/issues/56
- [x] [6. Provide a support URL](https://developers.zoom.us/docs/distribute/app-submission/submission-checklist/#6-provide-a-support-url)
- [x] [7. Provide a documentation URL](https://developers.zoom.us/docs/distribute/app-submission/submission-checklist/#7-provide-a-documentation-url)
- [ ] [8. Provide a Deauthorization event URL for testing](https://developers.zoom.us/docs/distribute/app-submission/submission-checklist/#8-provide-a-deauthorization-event-url-for-testing) | https://github.com/luni-ai/luni.ai/pull/42
- [x] [9. Optimize app data fetching](https://developers.zoom.us/docs/distribute/app-submission/submission-checklist/#9-optimize-app-data-fetching)
- [x] [10. Remove unused scopes from development](https://developers.zoom.us/docs/distribute/app-submission/submission-checklist/#10-remove-unused-scopes-from-development)
- [x] [11. Optimize app authentication and refresh flows](https://developers.zoom.us/docs/distribute/app-submission/submission-checklist/#11-optimize-app-authentication-and-refresh-flows)
- [x] [12. OAuth allow list](https://developers.zoom.us/docs/distribute/app-submission/submission-checklist/#12-oauth-allow-list)
- [x] [13. Specify the process to add your app](https://developers.zoom.us/docs/distribute/app-submission/submission-checklist/#13-specify-the-process-to-add-your-app)
- [ ] [14. Vendor Attestation: TDD and Evidence Documentation](https://developers.zoom.us/docs/distribute/app-submission/submission-checklist/#14-vendor-attestation-tdd-and-evidence-documentation)
  - [x] `x-zm-signature` not validated, checking with Karol
  - [x] Architecture diagram
- [x] [15. Personal data attestation](https://developers.zoom.us/docs/distribute/app-submission/submission-checklist/#15-personal-data-attestation)
- [x] [16. Secure confidential information](https://developers.zoom.us/docs/distribute/app-submission/submission-checklist/#16-secure-confidential-information)
- [x] [17. Developer contact information](https://developers.zoom.us/docs/distribute/app-submission/submission-checklist/#17-developer-contact-information)

- [ ] [1. Endpoint URL (Deauthorization notification)](https://marketplace.zoom.us/develop/apps/Lpv08ydqQSmdh1BL4OoH5Q/information?check=true)
- [x] [2. Scope usage description is required](https://marketplace.zoom.us/develop/apps/Lpv08ydqQSmdh1BL4OoH5Q/scope?check=true)
- [x] [3. Redirect URL for OAuth (Development)](https://marketplace.zoom.us/develop/apps/Lpv08ydqQSmdh1BL4OoH5Q/credentials?check=true)
- [x] [4. Technical Design - Missing required fields](https://marketplace.zoom.us/develop/apps/Lpv08ydqQSmdh1BL4OoH5Q/technical-design?check=true)

## [Step 2: Functionality, usability, and compliance review](https://developers.zoom.us/docs/distribute/app-review-process/#step-2-functionality-usability-and-compliance-review)

Status: N/A

- [ ] Functionality - We review your app's functionality and confirm that it works as you described. We confirm the installation and uninstallation processes, configuration settings, and user sign-up process. We also attempt to use the Zoom integration within your app to ensure data flow
- [ ] Usability
  - [ ] **Ads and analytics**: Your app should not present advertising to Zoom users or collect user information for marketing purposes. You can aggregate anonymous data for the purposes of running your business. See [Privacy and User Data Management](https://docs.google.com/document/d/1IQ14wA1ji49X3KAe-XSsEMl-NLtJhj7wZNDvFFnGGrQ/edit#heading=h.aelanp6gekuw) for more information.
  - [ ] **Be frictionless**: Your app should blend into the Zoom experience and not be a nuisance to users. Example: unnecessary pop-ups, unexpected computer audio, or spam.
  - [ ] **Be original**: Your app should not copy another app's functionality or design.
  - [ ] **Be transparent**: Clearly communicate the implications of using your app to users. A user should be able to understand what any interaction with the app will do, including what data will be collected and who it will be shared with.
- [ ] Compliance - Compliance review is done before security testing. We review your technical design documentation, including information you provide about your technology stack, architecture, and data handling; and verify compliance with Zoom's security and privacy requirements.

## [Step 3: Security](https://developers.zoom.us/docs/distribute/app-review-process/#step-3-security)

Comply with [Security Best Practices](https://developers.zoom.us/docs/distribute/security-best-practices/)

> This review looks at data transport and storage, and any potential exposure of sensitive data.

> As part of the submission review process, we **require documentation, and that evidence or attestation of your app's security solution be identified in the technical design document.**

Status: N/A
